### ISSUE TITLE
Return different response for a single command when run multiple times using same ssh session

### ISSUE THREAD

**Issue by ganeshrn** [tbotnz/cisshgo#27]
Is there a way to provide different outputs for same command? Example scenario can be 
1) Get response for running-config
2) Run dummy command to change config
3) Get updated running-config response

For step 1 and 3 same command will be used but expected response is different.

**Comment by tbotnz** [comment]
@ganeshrn thanks for the issue, there is currently no support for this other than changing the hostname. Can you provide some more information including examples for 1, 2 & 3. The implementation complexity would vastly depend on the level of understanding cisshgo would have to have for the step 2.

**Comment by lykinsbd** [comment]
## Design Options for Stateful Command Responses

### Option A — Sequence-based responses

Define an ordered list of transcript files per command. Each invocation returns the next response in the list; once exhausted, the last response is repeated.

**Schema** (new `command_sequences` field alongside existing `command_transcripts`):
```yaml
command_sequences:
  "show running-config":
    - "transcripts/cisco/csr1000v/running_config_initial.txt"
    - "transcripts/cisco/csr1000v/running_config_after_change.txt"
```

**How it works**: cisshgo tracks a per-session counter per command. First call → index 0, second call → index 1, etc. Once the list is exhausted, the last entry repeats.

**Pros**:
- Simple to implement (~100 lines)
- Fully backward compatible — existing `command_transcripts` unchanged
- No understanding of command semantics required
- Covers the stated use case (scripted test sequences)
- Easy to reason about and test

**Cons**:
- Sequence is fixed — doesn't respond to what commands were actually run between calls
- Not useful for non-deterministic test scenarios
- Counter is per-session, so parallel sessions each get their own independent sequence

**LOE**: Small — 1-2 days. Schema extension, custom YAML unmarshaling for the new field, per-session counter in `FakeDevice`, handler logic update.

---

### Option B — Trigger-based state transitions

Define named states, each with their own command response set. Commands can trigger transitions between states.

**Schema**:
```yaml
states:
  default:
    "show running-config": "transcripts/running_config_v1.txt"
  configured:
    "show running-config": "transcripts/running_config_v2.txt"

transitions:
  "ip address 10.0.0.1 255.255.255.0": "configured"
```

**How it works**: cisshgo maintains a current state per session. When a command matches a transition trigger, the state changes. Command responses are looked up from the current state's transcript map.

**Pros**:
- Responses actually reflect what commands were run
- More realistic simulation of device behavior
- Composable — multiple transitions can lead to the same state

**Cons**:
- Significantly more complex (~300-400 lines + new YAML schema)
- Requires defining a state machine per platform
- Transition matching uses the same fuzzy CmdMatch logic — ambiguous triggers could cause unexpected state changes
- Much harder to test exhaustively

**LOE**: Medium-large — 1-2 weeks. New state machine structs, YAML schema, per-session state tracking, transition matching, handler refactor, tests.

---

### Recommendation

Implement Option A first. It covers the stated use case, is low risk, and can ship independently. Option B can be tracked as a follow-on if users need trigger-based behavior. The two are additive — Option B could be layered on top of A later.

**Comment by lykinsbd** [comment]
## Updated Implementation Spec: Option A — Scenario-based Sequences

_Supersedes the previous spec comment. The design was revised after further discussion to improve ergonomics and correctly model sequential command ordering._

### Schema

Two top-level sections in `transcript_map.yaml` — `platforms` (unchanged) and a new `scenarios` section:

```yaml
platforms:
  csr1000v:
    vendor: "cisco"
    hostname: "cisshgo1000v"
    password: "admin"
    command_transcripts:
      "show version": "transcripts/cisco/csr1000v/show_version.txt"
      "show running-config": "transcripts/cisco/csr1000v/show_running-config.txt"
      "terminal length 0": "transcripts/generic_empty_return.txt"
    context_search: ...
    context_hierarchy: ...

scenarios:
  csr1000v-add-interface:
    platform: csr1000v          # inherits all command_transcripts from this platform
    sequence:
      - command: "show running-config"
        transcript: "transcripts/scenarios/csr1000v-add-interface/running_config_before.txt"
      - command: "interface GigabitEthernet0/0/2"
        transcript: "transcripts/generic_empty_return.txt"
      - command: "ip address 172.16.0.1 255.255.255.0"
        transcript: "transcripts/generic_empty_return.txt"
      - command: "end"
        transcript: "transcripts/generic_empty_return.txt"
      - command: "show running-config"
        transcript: "transcripts/scenarios/csr1000v-add-interface/running_config_after.txt"
```

Inventory references either a platform or a scenario — mutually exclusive:

```yaml
devices:
  - platform: csr1000v
    count: 10
  - scenario: csr1000v-add-interface
    count: 5
```

### New Types (`utils/argparsing.go`)

```go
type SequenceStep struct {
    Command    string `yaml:"command"`
    Transcript string `yaml:"transcript"`
}

type Scenario struct {
    Platform string         `yaml:"platform"`
    Sequence []SequenceStep `yaml:"sequence"`
}
```

`TranscriptMap` gains `Scenarios map[string]Scenario`.

`InventoryEntry` gains optional `Scenario string` — mutually exclusive with `Platform`. `LoadInventory` errors if both or neither are set.

### Data Model

`FakeDevice` is unchanged. The sequence lives entirely in the handler session closure — no state on the device.

New `InitScenario(scenarioName, transcriptMap, baseDir) (*FakeDevice, []SequenceStep, error)`:
- Resolves the scenario's platform, calls `InitGeneric` for the base device
- Returns the device plus pre-validated sequence steps

### Handler Changes

Per-session sequence pointer (`seqPointer int`) lives in the handler closure — resets on every new SSH connection.

In `dispatchCommand`:
1. If `seqPointer < len(sequence)` and input matches `sequence[seqPointer].command` via `CmdMatch`: return that step's transcript, advance pointer
2. Otherwise: fall through to normal `command_transcripts` behavior

### Validation

`ValidateTranscriptMap`:
- Validates all scenario transcript paths exist
- Validates each scenario's `platform` references a known platform

`LoadInventory`:
- Errors if an entry has both `platform` and `scenario` set
- Errors if an entry has neither set

### Out of Scope

- Cross-session state persistence — pointer resets on every new SSH connection. Future persistence use-cases are explicitly deferred.
- Trigger-based state transitions (Option B — see earlier design comment) are explicitly deferred. Option B can be layered on top in a future issue.
- Branching or conditional sequences — the sequence is strictly linear.
